### ISSUE TITLE
Typo in RemoveCourse Script for dhcpd

### ISSUE THREAD

**Issue by suryansh1** [vital2/vital-development#57]
The RemoveCourse script in /home/vital/vital2.0/source/virtual_lab/vital_site/vital/management/commands has a typo in when removing the dhcpd file.

It spells "dhcpd" as "dchpd", due to which the leases files are not cleared along with the rest of the course.

**Comment by reg1reg1** [comment]
Added this commit. Will merge to master on dev soon. This also has the new coursestats collection script added by you.
https://github.com/vital2/vital-development/commit/8cbfb78da7f045170c5e5f10bce7143fbb90a354

**Comment by reg1reg1** [comment]
https://github.com/vital2/vital-development/pull/58
has now been opened

**Comment by reg1reg1** [comment]
The changes have been reviewed and merged onto master.
